import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/font.toml",
  "~/.local/share/omakub/defaults/alacritty.toml",
  "~/dotfiles/.config/alacritty/keybindings.toml",
]

[font]
size = 12
